apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: us.gcr.io/dc-hughes-poc/controller_new:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      serviceAccountName: svc-test-init-container
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
